### PR TITLE
Add clone action to rest grid

### PR DESCRIPTION
**Pull request by lbwexler**

### CODE REVIEW

**Comment by lbwexler** [comment]
Seem like its a good start.  Can we build in to an admin grid (e.g. config grid?) to see what that looks like and have a built in example there right in hoist-react?

I do agree that this as a variant of 'add', and in particular closer to an 'add' that an 'edit'.  So I agree with your choice to return isAdd as `true` in this case. However very counter-intuitive to enter into it by reusing the openEdit() method.  Why not add an `openClone` method, or alternatively add an optional `clone` property to the the `openAdd` method?

**Comment by haynesjm42** [comment]
Closing in favor of https://github.com/exhi/hoist-react/pull/992 with master branch as target

**Comment by amcclain** [comment]
@haynesjm42 / @nadkarniarjun can we delete this branch?  I assume so but didn't want to jump the gun - please delete if not needed.

**Comment by haynesjm42** [comment]
Yes we can, doing so now.

**Pull request closed without merging**
