### PR TITLE
Percent formatter (and renderer) will multiply value by 100*,  Fixes: #1192

### PR DESCRIPTION
**Pull request by febbraiod**
Matches Excel behavior

+This will be a breaking change (and clean up to exportValue:  v => v/100 in appropriate cols) in client apps using it; should be added to changelog as such after merge

### CODE REVIEW

**Comment by amcclain** [comment]
Hi - can you please include a changelog entry in this pull request?  That way the change and the log entry both go in together - has been working well for these feature branch merges, especially when there is a breaking change.

**Comment by febbraiod** [comment]
Yes sorry, haven't worked in HR world a lot lately. Will do in a bit.

**Comment by lbwexler** [comment]
Should we wait for v. 25 for this?  This is a huge breaking change.

**Comment by amcclain** [comment]
Yes, I think so.  My thinking is that we put together a 24.2 release soon with some of the other changes in the pipeline, then the next time we have another breaking change we want to take to go along with this, we merge for v25.

Fortunately it should be easy to identify and adjust any usages, but I would expect there to be a few across the current crop of apps.

**Pull request merged**
