### PR TITLE
Update ag-grid from 20.1 -> 20.2

### PR DESCRIPTION
**Pull request by shravnk**
Signed-off-by: shravnk <brendan.ode4@gmail.com>

### CODE REVIEW

**Comment by amcclain** [comment]
Need yarn.lock in this PR as well - please run yarn install and push the changes there too!

Glad no other changes appear to be required.

**Comment by shravnk** [comment]
My bad - updated PR with lock file

**Comment by lbwexler** [comment]
I think this yarn.lock diff is bigger than it needs to be because your older version of yarn (<1.9?) is removing the integrity flag

**Comment by shravnk** [comment]
Thanks, had to upgrade yarn

**Pull request merged**
