### PR TITLE
Ensure Select shows all options when refocused

### PR DESCRIPTION
**Pull request by amcclain**
WIP proposal for #1140

### CODE REVIEW

**Comment by nadkarniarjun** [comment]
Tested this in Toolbox and confirmed that the fix works.

**Comment by amcclain** [comment]
Thanks Arjun for testing. 

@pauldelano and I ran into this bug yesterday reviewing a client app and it (understandably) surprised him. I would like to proceed with this fix unless anyone has a better approach - @lbwexler do you want to take a look? 

I had a sense we could do better somehow and avoid tracking this extra state, but I don't think it's terrible and believe the fix here is better than the bug 😄

**Comment by lbwexler** [comment]
PROMISE, I will look and merge this this afternoon.

**Comment by lbwexler** [comment]
Sorry for the delay here.  Looks promising!

**Pull request merged**
